[env:arduino_nano_esp32]
platform = espressif32
board    = arduino_nano_esp32
framework= arduino

build_flags =
    -DARDUINO_ARCH_ESP32
    -DBOARD_ESP32
    -DARDUINO_MAIN_TASK_STACK_SIZE=131072
    -DBOARD_HAS_PSRAM
    -O3
    -Wl,-no-check-sections

board_build.partitions = default_16MB.csv  ; PSRAM 지원

lib_deps =
    fraunhofer-ims/AIfES for Arduino @ ^2.2.0
    knolleary/PubSubClient @ ^2.8
    densaugeo/base64 @ ^1.4.0


[env:adafruit_feather_esp32s3]
platform = espressif32
board = adafruit_feather_esp32s3
framework = arduino

; --- PSRAM 활성화 ---
board_build.psram = yes

build_flags =
    -DARDUINO_ARCH_ESP32
    -DBOARD_ESP32
    -DARDUINO_MAIN_TASK_STACK_SIZE=262144
    -O3
    -Ofast
    -Wl,-no-check-sections
    -mfix-esp32-psram-cache-issue
    -DMQTT_MAX_PACKET_SIZE=32768

lib_deps =
    fraunhofer-ims/AIfES for Arduino @ ^2.2.0
    knolleary/PubSubClient @ ^2.8
    densaugeo/base64 @ ^1.4.0

[env:lolin_s3_pro]
platform = espressif32
board = lolin_s3_pro
framework = arduino

; PSRAM 활성화 설정
board_build.psram = yes
board_build.arduino.memory_type = qio_opi  ; ESP32-S3 OPI PSRAM 모드 활성화

board_build.usb_cdc_on_boot = 1  ; USB CDC 활성화

; 파티션 테이블 (16MB 플래시 사용)
board_build.partitions = default_16MB.csv

build_flags =
    -DARDUINO_ARCH_ESP32
    -DBOARD_ESP32
    -DARDUINO_MAIN_TASK_STACK_SIZE=131072
    -DBOARD_HAS_PSRAM
    -O3
    -Wl,-no-check-sections

lib_deps =
    fraunhofer-ims/AIfES for Arduino @ ^2.2.0
    knolleary/PubSubClient @ ^2.8
    densaugeo/base64 @ ^1.4.0